name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : 54.209.182.99
            USER_NAME : ubuntu
            
        run: |
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/Node-React-App &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master && cd server && pm2 start app.js
